In [0]:
from pyspark.sql import SparkSession

In [0]:
spark = SparkSession.builder.appName('miss').getOrCreate()

In [0]:
df = spark.read.format("csv").option('header',True).option('inferSchema', True).load("dbfs:/FileStore/shared_uploads/yashbhatia96@g.ucla.edu/ContainsNull.csv")

In [0]:
df.show()

In [0]:
#Dropping rows using .na
df.na.drop(how = 'any').show() #drops rows with any null values
df.na.drop(how = 'all').show() #drops rows only with all null values
df.na.drop(subset = ['Sales']).show() #drops rows with Sales column having null values
df.na.drop(thresh = 2).show() #drops rows only with at least 2 null values

In [0]:
#Filling missing data with fill
df.na.fill('No Name').show() #Spark automatically identifies the string columns and fill it with the string provided
df.na.fill(0).show() #Spark automatically identifies the integer columns and fill it with the number provided
df.na.fill('No Name', subset= ['Name']).show() #Specifying the name of the column in the subset parameter to fill the missing values -- Good Practice

In [0]:
#Filling null values with mean of values
from pyspark.sql.functions import mean
mean_val = df.select(mean(df['Sales'])).collect()[0][0]
print(mean_val)
df.na.fill(mean_val,subset = ['Sales']).show()